// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 3
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 5
// type_id es ____ 2
// type_id es ____ 4
// type_id es ____ 2
// type_id es ____ 3
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 1
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 6
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 1
// type_id es ____ 2
// type_id es ____ 7
// type_id es ____ 2
// type_id es ____ 6
// type_id es ____ 6
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 6
// type_id es ____ 6
// type_id es ____ 2
// type_id es ____ 6
// type_id es ____ 2
// type_id es ____ 4
// type_id es ____ 6
// type_id es ____ 8
// type_id es ____ 9
// type_id es ____ 6
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 6
// type_id es ____ 6
// type_id es ____ 2
// type_id es ____ 6
// type_id es ____ 5
// type_id es ____ 2
// type_id es ____ 6
// type_id es ____ 1
// type_id es ____ 6
// type_id es ____ 2
// type_id es ____ 4
// type_id es ____ 6
// type_id es ____ 6
// type_id es ____ 6
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 10
// type_id es ____ 8
// type_id es ____ 2
// type_id es ____ 11
// type_id es ____ 1
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 12
// type_id es ____ 6
// type_id es ____ 4
// type_id es ____ 10
// type_id es ____ 4
// type_id es ____ 4
// type_id es ____ 3
// type_id es ____ 6
// type_id es ____ 2
// type_id es ____ 2
// type_id es ____ 13
// type_id es ____ 14

